### PR TITLE
Update bindgen dependency

### PR DESCRIPTION
**Pull request by AldaronLau**
Updates bindgen to 0.60

### CODE REVIEW

**Comment by AldaronLau** [comment]
Just realized this would require a MSRV bump to 1.54, would that be a problem?

**Comment by jmagnuson** [comment]
>Just realized this would require a MSRV bump to 1.54, would that be a problem?

Nah, that's fine.

**Comment by gharveymn** [comment]
Bump. The transitive dependency `ansi_term` is now unmaintained.

**Comment by jmagnuson** [comment]
Closing in favor of #20.

**Pull request closed without merging**
