### PR TITLE
Update `bindgen` version in libevent-sys Cargo.toml

### PR DESCRIPTION
**Pull request by klebs6**
0.60 --> 0.69 to fix crashing build on osx

### CODE REVIEW

**Comment by klebs6** [comment]
I just realized that 0.69 does not seem to exist on all systems.  perhaps we can use 0.65? i will check to see if using 0.65 fixes the original error on osx now

**Comment by klebs6** [comment]
hmm, looks like there is another problem with the build on ubuntu because of the regex crate version on an older rustc.  i will investigate

**Comment by klebs6** [comment]
not quite sure why we fail the CI build yet.  i tried a few debugging steps.  I will likely look at this some more later on today

**Comment by klebs6** [comment]
super stumped 😂

**Comment by klebs6** [comment]
Screenshot 2024-06-20 at 8 37 24 PM


In the bindgen crate, "logging" is indeed another feature, even though it also appears in the defaults.  I am not sure yet what to do about this error.  Maybe somebody here knows how this can be solved.

**Comment by AldaronLau** [comment]
@klebs6 Not sure exactly why, but it looks like CI is pulling in Rust 1.6.0 instead of Rust 1.60 for some reason (bug in actions-rs or yaml weirdness, maybe?), maybe try `1.60.0`?

**Comment by klebs6** [comment]
> @klebs6 Not sure exactly why, but it looks like CI is pulling in Rust 1.6.0 instead of Rust 1.60 for some reason (bug in actions-rs or yaml weirdness, maybe?), maybe try `1.60.0`?

brilliant!! thanks! that was it! it turns out, we need 1.65.0 to satisfy the msrv for the deps!

**Comment by jmagnuson** [comment]
LGTM, thanks @klebs6 and @AldaronLau!

**Pull request merged**
